[workspace]
members = [
    "rustycrab-api",
    "rustycrab-model",
    "rustycrab-webapp",
    "database-migration",
    "spotify-api",
]

resolver = "2"

[workspace.package]
authors = ["Khai Nguyen"]
