//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "bot_guild_welcomes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub enabled: i8,
    #[sea_orm(column_name = "welcomeChannelID")]
    pub welcome_channel_id: Option<String>,
    #[sea_orm(column_name = "welcomeContent", column_type = "Text", nullable)]
    pub welcome_content: Option<String>,
    #[sea_orm(column_name = "messageType")]
    pub message_type: String,
    #[sea_orm(column_name = "botBotID")]
    pub bot_bot_id: Option<String>,
    #[sea_orm(column_name = "guildGuildID")]
    pub guild_guild_id: Option<String>,
    #[sea_orm(column_name = "embedInfoId", unique)]
    pub embed_info_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::bots_info::Entity",
        from = "Column::BotBotId",
        to = "super::bots_info::Column::BotId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    BotsInfo,
    #[sea_orm(
        belongs_to = "super::embed_info::Entity",
        from = "Column::EmbedInfoId",
        to = "super::embed_info::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    EmbedInfo,
    #[sea_orm(
        belongs_to = "super::guild_info::Entity",
        from = "Column::GuildGuildId",
        to = "super::guild_info::Column::GuildId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    GuildInfo,
}

impl Related<super::bots_info::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BotsInfo.def()
    }
}

impl Related<super::embed_info::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EmbedInfo.def()
    }
}

impl Related<super::guild_info::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GuildInfo.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
