//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "items")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_name = "itemID")]
    pub item_id: i32,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub emoji: Option<String>,
    pub value: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub functions: String,
    #[sea_orm(column_name = "botBotID")]
    pub bot_bot_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::bots_info::Entity",
        from = "Column::BotBotId",
        to = "super::bots_info::Column::BotId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    BotsInfo,
    #[sea_orm(has_many = "super::marriage::Entity")]
    Marriage,
}

impl Related<super::bots_info::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BotsInfo.def()
    }
}

impl Related<super::marriage::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Marriage.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
