//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

pub mod prelude;

pub mod auto_responses;
pub mod booking_activities;
pub mod booking_player;
pub mod bookingbot_settings;
pub mod bot_guild_configurations;
pub mod bot_guild_logs;
pub mod bot_guild_welcomes;
pub mod bot_user_info;
pub mod bots_info;
pub mod embed_info;
pub mod gambling_settings;
pub mod guild_info;
pub mod items;
pub mod marriage;
pub mod test_users;
pub mod twitch_follows;
pub mod user_info;
