//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "items")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_name = "itemID")]
    pub item_id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub emoji: Option<String>,
    pub value: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub functions: String,
    #[sea_orm(column_name = "botId")]
    pub bot_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::bots::Entity",
        from = "Column::BotId",
        to = "super::bots::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Bots,
    #[sea_orm(has_many = "super::marriages::Entity")]
    Marriages,
}

impl Related<super::bots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Bots.def()
    }
}

impl Related<super::marriages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Marriages.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
