//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "log_ignore_roles")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_name = "roleID")]
    pub role_id: String,
    #[sea_orm(column_name = "logSettingId")]
    pub log_setting_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::log_settings::Entity",
        from = "Column::LogSettingId",
        to = "super::log_settings::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    LogSettings,
}

impl Related<super::log_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LogSettings.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
