//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "log_settings")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_name = "specifyChannels")]
    pub specify_channels: i8,
    #[sea_orm(column_name = "newAccountAge")]
    pub new_account_age: i32,
    #[sea_orm(column_name = "botId")]
    pub bot_id: i32,
    #[sea_orm(column_name = "guildId")]
    pub guild_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::bots::Entity",
        from = "Column::BotId",
        to = "super::bots::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Bots,
    #[sea_orm(
        belongs_to = "super::guild_info::Entity",
        from = "Column::GuildId",
        to = "super::guild_info::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    GuildInfo,
    #[sea_orm(has_many = "super::log_ignore_channels::Entity")]
    LogIgnoreChannels,
    #[sea_orm(has_many = "super::log_ignore_roles::Entity")]
    LogIgnoreRoles,
}

impl Related<super::bots::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Bots.def()
    }
}

impl Related<super::guild_info::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GuildInfo.def()
    }
}

impl Related<super::log_ignore_channels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LogIgnoreChannels.def()
    }
}

impl Related<super::log_ignore_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LogIgnoreRoles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
